pipeline {
	agent any
	stages {
		stage('Checkout') {
			steps {
				git url: 'git@github.com:vanthiyadhevan/playwright_python.git', branch: 'terraform', credentialsId: 'vanthiyadhevan'
				// git url: 'https://github.com/vanthiyadhevan/playwright_python.git', branch: 'main'
			}
		}
		stage ('Terraform Init') {
			steps {
				sh 'terraform init'
			}
		}
		stage ('Terraform Validate') {
			steps {
				sh "terraform validate"
			}
		}
		stage ('Terraform Apply') {
			steps {
				script {
					withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', accessKeyVariable: 'AWS_ACCESS_KEY_ID', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY', credentialsId: 'awscreds']]) {
    sh 'terraform apply'
}

				}
			}
		}
	}
}
